security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    role_hierarchy:
        ROLE_EDITEUR:      ROLE_USER
        ROLE_MANAGER:      ROLE_EDITEUR
        ROLE_RESPONSABLE:  ROLE_MANAGER
        ROLE_DEVELOPPEUR:  ROLE_RESPONSABLE
        ROLE_FONDATEUR:    ROLE_DEVELOPPEUR

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            login_throttling:
                max_attempts: 5
                interval: '15 minutes'

            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
                enable_csrf: true

            logout:
                path: app_logout
                target: app_home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check

            custom_authenticators:
                - App\Security\SteamAuthenticator

            entry_point: form_login

    access_control:
        - { path: ^/2fa, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/api/, roles: PUBLIC_ACCESS }
        - { path: ^/profil, roles: ROLE_USER }
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/mes-serveurs, roles: ROLE_USER }
        - { path: ^/serveur/ajouter, roles: ROLE_USER }
        - { path: ^/serveur/\d+/(modifier|gestion|supprimer|regenerate-token), roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_EDITEUR }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
